AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Stack for QRGenerator Backend"

Parameters:
  EnvNameParam:
    Type: String
    Description: "The environment name"
  S3BUCKETDB:
    Type: String
    Description: "The S3 bucket name for the database"
  S3KEYDB:
    Type: String
    Description: "The S3 key for the database"
  SLACKTOKEN:
    Type: String
    Description: "The S3 key for the database"

Globals:
  Function:
    Runtime: python3.11
    Handler: app.lambda_handler
    Timeout: 180
    Layers:
      - !Ref QRUtilLayer
    Environment:
      Variables:
        ENV_NAME: !Ref EnvNameParam
        BUCKET_NAME: !Ref S3BUCKETDB
        S3_KEY: !Ref S3KEYDB
        SLACKBOTKEY: !Ref SLACKTOKEN

Resources:
  # Buckets
  QrCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-bucket-qr-database

  QrGenratorApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "QrGeneratorApi"
      StageName: "Prod"
      Cors:
        AllowMethods: "'POST,OPTIONS,GET'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
  
  # Lambda Functions
  GenerateQrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/generate_qr/
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BUCKETDB
      Events:
        GenerateQrApi:
          Type: Api
          Properties:
            Path: /generate
            Method: post
            RestApiId:
              Ref: QrGenratorApi

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/redirect/
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BUCKETDB
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /redirect/{qr_id}
            Method: get
            RestApiId:
              Ref: QrGenratorApi

  QrCleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/qr_cleanup
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BUCKETDB
      EventInvokeConfig:
        MaximumRetryAttempts: 2
      Events:
        CronJobEvent:
          Type: Schedule
          Properties:
            Name:
              Fn::Sub: ${AWS::StackName}-CronEvent
            Schedule: cron(0 17 ? * 2 *)

  QRUtilLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: QRUtility
      Description: QR dependencies
      ContentUri: layer
      CompatibleRuntimes:
        - python3.11
        - python3.10
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
      

Outputs:
  GenerateQrApi:
    Description: "API Gateway endpoint URL for Generate QR Code function"
    Value: !Sub "https://${QrGenratorApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"
  RedirectApi:
    Description: "API Gateway endpoint URL for Redirect function"
    Value: !Sub "https://${QrGenratorApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/redirect/"